### ISSUE TITLE
Matlab help()

### ISSUE THREAD

**Issue by tsdev** [bastibe/transplant#43]
This is not really an issue, but a question. In a deployed Matlab code the help() function is blocked, so I created an alternative function that generates the help script with the same header as the original help:
```
helpStr = help(functionName)
```
Do you know what would be the easiest way to redefine the \_\_doc\_\_ method in python to call the alternative command? It seems by creating a user function with the same name does not help. Could you provide an additional argument in Matlab() to define the help function / make some fixed alternative name.

Thanks!

**Comment by bastibe** [comment]
This is already implemented for functions/methods and objects. `__doc__` should be populated, and  typical documentation tools, like the `?` operator in IPython, should work as expected.

Unless your compilation process strips documentation?

I didn't even know `help` existed in Python. Upon using it, it seems to return the wrong docstring, though (the one from the type, as opposed to the one from the object). I haven't found a nice way of changing that, yet.

If you're curious, all Matlab functions and objects are represented as objects by Transplant, since that allows me to fetch `__doc__` on demand only. This is a nice optimization, since fetching documentation is actually quite time-consuming. It does seem to break `help`, though. I actually have a fix for functions in 8b0d602, but I don't yet know how to solve this issue for `MatlabProxyObject`s.

**Comment by tsdev** [comment]
I have to specify better what I mean. The problem is in the deployed Matlab code, where the `help()` function is blocked. In `transplant_master.py` the call:
```
def __doc__(_self):
                return self.help(data[1], nargout=1)
```
errors out, becase `self.help()` does not exists. My solution is that a created a new `helps.m` function which produces the help string in Matlab. The only problem is that transplant needs to be modified for this (even if a create a help.m function, it is not callable).

**Comment by bastibe** [comment]
Your compilation story gets ever more complex!

I guess you could subclass `Matlab` and override `_decode_function` and `ProxyObject` with versions that don't fetch help. You could then use your subclass in lieu of the original `Matlab`, without requiring a change in Transplant.

Alternatively, we could change Matlab to behave gracefully if no `help` function is available, but that wouldn't allow an alternative help provider. In that case, we could even try to provide help by parsing the source files manually, but I guess this would fail in your case as well, since the original source files would not be available and are probably not discoverable.

**Comment by tsdev** [comment]
Thanks, this gave some ideas. I think I can just modify transplant_remote.m in a way that it translates help() --> helps() automatically. I think this can be considered closed. :)
