### ISSUE TITLE
Howto get remote working?

### ISSUE THREAD

**Issue by nbecker** [bastibe/transplant#55]
import transplant
matlab = transplant.Matlab(address='127.0.0.1',executable='/home/nbecker/.local/bin/matlab')#jvm=False)

...
	Trial License -- for use to evaluate programs for possible purchase as an end-user only.

Undefined function or variable 'transplant_remote'.

Sorry if this is a stupid question - I don't know anything about matlab.  I'm guessing it isn't finding the needed .m file, but I don't know how to fix that.

**Comment by bastibe** [comment]
Transplant will try to tell Matlab the location of the needed .m files. This can only work on a local file system, though. Since you added `address=...`, it assumes that you are trying to open Matlab on a remote machine. Thus Matlab doesn't know the location of the .m files. 

Since you are doing this on your local machine, you don't need to specify an `address`. That should fix it.

**Comment by nbecker** [comment]
Thanks, but I'm using 127.0.0.1 just as a test :)  Do you know how to make
this work?
