### ISSUE TITLE
Consider adding transplant to conda forge

### ISSUE THREAD

**Issue by kupiqu** [bastibe/transplant#76]
https://conda-forge.org/#about

A better integration with conda might potentially fix issues when using transplant in conda environments, e.g. issue #75

**Comment by bastibe** [comment]
Transplant is a pure-Python module and does not need compilation at all. What benefits would it bring to host it on conda-forge in addition to PyPi?

Personally, I have switched back to using PyPi instead of conda a few years ago, when wheels finally became usable. I don't believe #75 is related to installation issues, though.

**Comment by kupiqu** [comment]
> Transplant is a pure-Python module and does not need compilation at all. What benefits would it bring to host it on conda-forge in addition to PyPi?
> 
> Personally, I have switched back to using PyPi instead of conda a few years ago, when wheels finally became usable. I don't believe #75 is related to installation issues, though.

Sure. It was not a matter of compilation but of awareness inside conda's environments. But I solved it by installing it once inside the environment by using (installing) conda's PyPi.
